// Define the question type
export interface Question {
  id: string
  text: string
  options: string[]
  correctAnswer: string
  lastAnswered?: number
  lastShown?: number
  correctCount: number
  incorrectCount: number
}

// Define the category type
export interface Category {
  id: string
  name: string
  questions: Question[]
}

// Define the app data structure
export interface QuizData {
  version: number
  categories: Category[]
  activeCategory: string
}

// Sample data with multiple categories
export const sampleData: QuizData = {
  version: 2,
  categories: [
    {
      id: 'life',
      name: 'Můj život',
      questions: [
        {
          id: 'q13',
          text: 'Co všechno kryje pojištění Hospitalizace úrazem?',
          options: [
            'Pobyt v nemocnici, lázních, léčebnách, ozdravovnách, rehabilitačních ústavech, LDN a hospicích z důvodu úrazu',
            'Pobyt v nemocnici z důvodu nemoci',
            'Pobyt v nemocnici z důvodu nemoci a úrazu',
          ],
          correctAnswer: 'Pobyt v nemocnici, lázních, léčebnách, ozdravovnách, rehabilitačních ústavech, LDN a hospicích z důvodu úrazu',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q38',
          text: 'Plníme z pojištění Pracovní neschopnosti i za pracovní úrazy a nemoci?',
          options: ['Ano, ale pouze za nemoci z povolání', 'Ano', 'Ne'],
          correctAnswer: 'Ano',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q60',
          text: 'Pokud dojde k úrazu při konání vybraných adrenalinových činností, které jsou uvedeny v benefitu Neplánový adrenalin, dojde k poj. plnění z těchto rizik:',
          options: [
            'Hospitalizace úrazem, Následky závažného úrazu, Smrt úrazem',
            'Hospitalizace úrazem, Trvalé následky úrazu, Smrt úrazem, Pracovní neschopnost',
            'Hospitalizace úrazem, Trvalé následky úrazu, Smrt úrazem, Doba nezbytného léčení',
          ],
          correctAnswer: 'Hospitalizace úrazem, Trvalé následky úrazu, Smrt úrazem, Pracovní neschopnost',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q3',
          text: 'Kdo má právo na plnění z pojištění Můj život 2 v případě smrti pojištěného?',
          options: ['Manžel, manželka', 'Pojistník', 'Obmyšlený, pokud není určen, tak osoby určené podle § 2831 občanského zákoníku'],
          correctAnswer: 'Obmyšlený, pokud není určen, tak osoby určené podle § 2831 občanského zákoníku',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q37',
          text: 'Jaká je maximální progrese u Trvalých následků úrazu?',
          options: ['Trvalé následky jsou vždy bez progresivního plnění', '1000 %', '800 %'],
          correctAnswer: '1000 %',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q104',
          text: 'Jaká je čekací doba u Pojištění asistované reprodukce?',
          options: ['12 měsíců', '6 měsíců', '2 měsíce'],
          correctAnswer: '2 měsíce',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q77',
          text: 'Umožňuje pojištění Můj život 2 mimořádné výběry?',
          options: ['Ano, 12x ročně u investiční varianty', 'Ano, 1x ročně u rizikové varianty', 'Ne'],
          correctAnswer: 'Ano, 12x ročně u investiční varianty',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q102',
          text: 'Jaké všechny podmínky musí splňovat oprávněná osoba, aby bylo plněno při pojistné události z pojištění Ošetřování dítěte?',
          options: [
            'Musí mít příjem jako zaměstnanec nebo OSVČ, je uveden na dokladu o ošetřování jako žadatel o dávku, resp. osoba, která ošetřuje pojištěného',
            'Musí mít příjem jako zaměstnanec nebo OSVČ, nepobírá peněžitou pomoc v mateřství nebo rodičovský příspěvek, je uveden na dokladu o ošetřování jako žadatel o dávku, resp. osoba, která ošetřuje pojištěného, musí nahlásit PU bez zbytečného odkladu',
            'Nepobírá peněžitou pomoc v mateřství nebo rodičovský příspěvek, musí nahlásit PU bez zbytečného odkladu',
          ],
          correctAnswer:
            'Musí mít příjem jako zaměstnanec nebo OSVČ, nepobírá peněžitou pomoc v mateřství nebo rodičovský příspěvek, je uveden na dokladu o ošetřování jako žadatel o dávku, resp. osoba, která ošetřuje pojištěného, musí nahlásit PU bez zbytečného odkladu',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q97',
          text: 'Od kterého dne vyplácíme denní dávku v případě ošetřování dítěte?',
          options: ['Od 28. dne', 'Od 10. dne', 'Od 16. dne'],
          correctAnswer: 'Od 10. dne',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q27',
          text: 'Jaká je čekací doba u pojištění Ztráta soběstačnosti pro pojištěné dítě?',
          options: ['0 měsíců', '6 měsíců, u úrazu odpadá', '12 měsíců'],
          correctAnswer: '0 měsíců',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q16',
          text: 'Do kdy plníme za smrt úrazem a za smrt při dopravní nehodě?',
          options: [
            'Plníme za smrt, ke které dojde ihned při PU',
            'Plníme za smrt, ke které dojde do 3 let od PU',
            'Plníme za smrt, ke které dojde do 1 roku od PU',
          ],
          correctAnswer: 'Plníme za smrt, ke které dojde do 3 let od PU',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q63',
          text: 'Pokud dojde ke změně diagnózy v rámci jedné neschopenky:',
          options: ['Nenabíhá nová karenční doba', 'Nelze uplatnit plnění ani na první stanovenou diagnózu', 'Nabíhá nová karenční doba'],
          correctAnswer: 'Nenabíhá nová karenční doba',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q59',
          text: 'Benefit Program proti rakovině je sjednán automaticky vždy:',
          options: [
            'Když je sjednaná pojistná částka pro případ závažného onemocnění min. 200 000 Kč',
            'Když je sjednané pojištění Závažného onemocnění',
            'Když je sjednaná pojistná částka pro případ závažného onemocnění min. 100 000 Kč',
          ],
          correctAnswer: 'Když je sjednaná pojistná částka pro případ závažného onemocnění min. 200 000 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q81',
          text: 'Jaké je minimální pojistné v pojištění Můj život 2?',
          options: ['200 Kč', 'Riziková část 300 Kč + investiční část min. 100 Kč', 'Riziková část 300 Kč + investiční část min. 1 Kč'],
          correctAnswer: 'Riziková část 300 Kč + investiční část min. 1 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q118',
          text: 'Plníme při výplatě za pojistnou událost, ošetřování dospělého, i za pobyt dospělého v nemocnici?',
          options: ['Ano', 'Ne. Je hrazeno ČSSZ', 'Ano. Ale jen v případě hospitalizace úrazem'],
          correctAnswer: 'Ano',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q121',
          text: 'Jaký je limit plnění v případě pojistné události ošetřování dospělého pro OSVČ?',
          options: ['Max. 90 dnů na PU a pojistný rok', 'Max. 30 dnů na PU a pojistný rok', 'Max. 60 dnů na PU a pojistný rok'],
          correctAnswer: 'Max. 90 dnů na PU a pojistný rok',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q71',
          text: 'Pro koho je určen brand Můj život PROFI 2?',
          options: [
            'Pro studenty',
            'Pro klienty, kteří chtějí pouze využít maximalizaci daňových výhod životního pojištění',
            'Pro zaměstnance firem v korporátním segmentu, kterým na smlouvy přispívá zaměstnavatel',
          ],
          correctAnswer: 'Pro zaměstnance firem v korporátním segmentu, kterým na smlouvy přispívá zaměstnavatel',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q58',
          text: 'A Lze sjednat benefit Program proti rakovině bez zkoumání zdravotního stavu?',
          options: ['Ne', 'Ano', 'Ano od pojistné částky 200 000 Kč'],
          correctAnswer: 'Ano',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q67',
          text: 'Jaké je minimální pojistné v brandu Můj život na PENZI 2?',
          options: [
            '300 Kč',
            '100 Kč za celou poj. smlouvu do investic + pojistné za povinnou smrt',
            '200 Kč za celou poj. smlouvu do investic + pojistné za povinnou smrt',
          ],
          correctAnswer: '200 Kč za celou poj. smlouvu do investic + pojistné za povinnou smrt',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q2',
          text: 'Za jakých podmínek, při sjednané variantě s plněním od 1. dne, lze vyplácet denní dávku v případě pracovní neschopnosti?',
          options: [
            'Pokud se jedná o pracovní neschopnost v případě úrazu',
            'Po uplynutí sjednané karenční doby',
            'Po uplynutí sjednané karenční doby a po min. 24 hod. hospitalizaci',
          ],
          correctAnswer: 'Po uplynutí sjednané karenční doby',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q50',
          text: 'V případě pracovní neschopnosti z důvodu jednoho těhotenství je uhrazena doba plnění:',
          options: ['14 dní', '90 dní', '30 dní'],
          correctAnswer: '30 dní',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q5',
          text: 'Jaká je čekací doba u pojištění Invalidní renta?',
          options: ['3 měsíce v případě nemoci, 3 dny v případě úrazu', '0 měsíců', '12 měsíců, v případě úrazu odpadá'],
          correctAnswer: '0 měsíců',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q85',
          text: 'Jaké jsou podmínky pro získání Bonusu za věrnost?',
          options: [
            'Min. pojistné 500 Kč a pojistná částka na riziko Smrti min. 20 000 Kč (po celou dobu trvání smlouvy)',
            'Průměrné měs. pojistné za sjednaná pojištění po slevě min. 800 Kč a pojistná doba delší jak 10 let (podmínky výše měs. pojistného musí být splněny při uzavření nebo při změně poj. smlouvy)',
            'Min. pojistné 500 Kč a pojistná doba delší jak 10 let',
          ],
          correctAnswer:
            'Průměrné měs. pojistné za sjednaná pojištění po slevě min. 800 Kč a pojistná doba delší jak 10 let (podmínky výše měs. pojistného musí být splněny při uzavření nebo při změně poj. smlouvy)',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q109',
          text: 'Čekací doba pro riziko Ošetřování dítěte je:',
          options: ['2. měsíce od sjednání', '1. měsíc od sjednání', '6. měsíců od sjednání'],
          correctAnswer: '2. měsíce od sjednání',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q54',
          text: 'OPCE znamená?',
          options: [
            'Možnost v průběhu trvání pojištění bez zkoumání zdravotního stavu navýšit libovolně pojistnou částku u vybraných pojištění',
            'Možnost v průběhu trvání pojištění bez zkoumání zdravotního stavu navýšit pojistnou částku až o 50 % u vybraných pojištění',
            'Možnost v průběhu trvání pojištění bez zkoumání zdravotního stavu navýšit pojistnou částku o 30 % u vybraných pojištění',
          ],
          correctAnswer:
            'Možnost v průběhu trvání pojištění bez zkoumání zdravotního stavu navýšit pojistnou částku až o 50 % u vybraných pojištění',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q44',
          text: 'Jakou formou, kdy a za jakých podmínek dojde k plnění z pojištění Následky závažného úrazu:',
          options: [
            'Jednorázová výplata poj. částky při trvalém poškození těla alespoň 50 %, která se vyplácí až po ustálení následků po jednom roce',
            'Jednorázová výplata poj. částky při trvalém poškození těla alespoň 60 %, která se vyplácí až po ustálení následků po třech letech',
            'Jednorázová výplata poj. částky při trvalém poškození těla alespoň 65 %, která se vyplácí až po ustálení následků po půl roce',
          ],
          correctAnswer:
            'Jednorázová výplata poj. částky při trvalém poškození těla alespoň 50 %, která se vyplácí až po ustálení následků po jednom roce',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q98',
          text: 'Plníme při výplatě za pojistnou událost, ošetřování dítěte, i za pobyt dítěte v nemocnici?',
          options: ['Ano. Ale jen v případě hospitalizace úrazem', 'Ano', 'Ne. Je hrazeno ČSSZ'],
          correctAnswer: 'Ano',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q31',
          text: 'Odpojistí se varianta Závažného onemocnění po výplatě za jedno závažné onemocnění?',
          options: [
            'Ne. Odpojistí se pouze příslušná skupina diagnóz, která může být v příčinné souvislosti s PU, varianta nezaniká.',
            'Ne',
            'Ano',
          ],
          correctAnswer: 'Ne. Odpojistí se pouze příslušná skupina diagnóz, která může být v příčinné souvislosti s PU, varianta nezaniká.',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q94',
          text: 'Kdy vzniká nárok na výplatu Věrnostního bonusu?',
          options: ['Při dožití a úmrtí povinného pojištěného', 'Po 10 letech trvání poj. smlouvy', 'Jen při dožití smlouvy'],
          correctAnswer: 'Při dožití a úmrtí povinného pojištěného',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q108',
          text: 'Čekací doba pro riziko Hospitalizace:',
          options: ['1. měsíc od sjednání', '6. měsíců od sjednání', '2. měsíce od sjednání'],
          correctAnswer: '2. měsíce od sjednání',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q4',
          text: 'Pojištění Trvalých následků úrazu můžeme sjednat:',
          options: ['Pouze bez progrese', 'Pouze s progresí', 'S progresí i bez progrese'],
          correctAnswer: 'Pouze s progresí',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q21',
          text: 'Jaké všechny varianty výplat nabízíme u pojištění Ztráty soběstačnosti pro děti?',
          options: [
            'Jednorázovou výplatu PČ, Rentu do 18 let věku dítěte, Rentu na 30 let od PU',
            'Jednorázovou výplatu PČ, Rentu do 18 let věku dítěte',
            'Jednorázovou výplatu PČ, Rentu na 30 let od PU',
          ],
          correctAnswer: 'Jednorázovou výplatu PČ, Rentu na 30 let od PU',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q6',
          text: 'Pojistné plnění za Následky závažného úrazu se vyplácí?',
          options: [
            'Jednorázově, po prvním roce, zanechá-li úraz trvalé následky podle Oceňovacích tabulek B ve výši 50% a více % a to v součtu jednotlivých trvalých následků',
            'Jednorázově podle diagnózy stanovené min.65% poškození těla v Oceňovacích tabulkách B a je podmíněno výplatou invalidního důchodu',
            'Jednorázově podle diagnózy stanovené min.50% poškození těla v Oceňovacích tabulkách B a je podmíněno výplatou invalidního důchodu',
          ],
          correctAnswer:
            'Jednorázově, po prvním roce, zanechá-li úraz trvalé následky podle Oceňovacích tabulek B ve výši 50% a více % a to v součtu jednotlivých trvalých následků',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q100',
          text: 'Jaký je limit plnění v případě pojistné události ošetřování dítěte pro zaměstnance?',
          options: [
            'Max. 60 dnů (max.180 dnů za pojistný rok)',
            'Max. 90 dnů na PU (max. 180 dnů za pojistný rok)',
            'Max. 30 dnů na PU a pojistný rok',
          ],
          correctAnswer: 'Max. 90 dnů na PU (max. 180 dnů za pojistný rok)',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q41',
          text: 'Pojištění Závažná poranění zaniká po výplatě pojistného plnění.',
          options: ['Ano', 'Ne', 'Ano, ale jen v případě, kdy došlo k plnění z rozšířené varianty'],
          correctAnswer: 'Ne',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q89',
          text: 'Jaká je min. pojistná částka u pojištění Smrti?',
          options: [
            '10 000 Kč',
            '100 000 Kč',
            '1 000 Kč u rizikové varianty, u investiční varianty min. 10 000 Kč pro povinného pojištěného',
          ],
          correctAnswer: '1 000 Kč u rizikové varianty, u investiční varianty min. 10 000 Kč pro povinného pojištěného',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q46',
          text: 'Doba výplaty pro Rentu do roku (do věku obmyšleného), v případě smrti, začína běžet:',
          options: [
            'Od smrti pojištěného, po sjednanou dobu výplaty (2 – 25 let)',
            'Od sjednání poj. smlouvy, po sjednanou dobu výplaty (2 – 25 let)',
            'Rentu do roku v případě smrti nelze sjednat',
          ],
          correctAnswer: 'Od sjednání poj. smlouvy, po sjednanou dobu výplaty (2 – 25 let)',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q20',
          text: 'Jaký je minimální vstupní věk dítěte u pojištění Ztráty soběstačnosti?',
          options: ['12 měsíců', '6 týdnů', '2 roky'],
          correctAnswer: '12 měsíců',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q27',
          text: 'Jaká je čekací doba u pojištění Ztráta soběstačnosti pro pojištěné dítě?',
          options: ['6 měsíců, u úrazu odpadá', '0 měsíců', '12 měsíců'],
          correctAnswer: '0 měsíců',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q93',
          text: 'Z čeho se počítá sleva za propojištěnost?',
          options: [
            'Z brutto pojistného úrazových rizik',
            'Z bruttopojistného životních rizik + pracovní neschopnosti',
            'Z pojistného za poj. domácnosti, stavby a PMV',
          ],
          correctAnswer: 'Z bruttopojistného životních rizik + pracovní neschopnosti',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q111',
          text: 'Diagnóza Rakovina ve stadiu in-situ je zahrnuta:',
          options: [
            'V Rozšířené variantě pro dospělé i děti',
            'Pouze v Rozšířené variantě pro děti',
            'Pouze v Rozšířené variantě pro dospělé',
          ],
          correctAnswer: 'V Rozšířené variantě pro dospělé i děti',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q32',
          text: 'V pojištění Ztráta soběstačnosti pro dospělou osobu můžeme klienta pojistit na:',
          options: [
            'II.+III.+ IV. stupeň – PČ ,II.+III.+IV. stupeň – renta do 18 let',
            'II.+III.+ IV. stupeň – PČ, II.+III.+ IV. stupeň – renta na 30 let a Zproštění od placení v případě ztráty soběstačnosti II.+III.+ IV. st.',
            'II.+III.+ IV. stupeň – renta na 30 let, Zproštění od placení v případě ztráty soběstačnosti II.+III.+ IV. st.',
          ],
          correctAnswer:
            'II.+III.+ IV. stupeň – PČ, II.+III.+ IV. stupeň – renta na 30 let a Zproštění od placení v případě ztráty soběstačnosti II.+III.+ IV. st.',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q91',
          text: 'O kolik % ročně se navýší pojistné z důvodu indexace:',
          options: ['Každý rok min. o 4 %', 'Každý rok min. o 4,2 %', 'Každý rok min. o 2,4 %'],
          correctAnswer: 'Každý rok min. o 4 %',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q40',
          text: 'Jaká je územní platnost pro hopspitalizaci v rehabilitačních zařízeních, LDN ... ?',
          options: ['Svět', 'Evropská unie', 'ČR'],
          correctAnswer: 'Svět',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q66',
          text: 'Brand Můj život na PENZI 2 je určen?',
          options: [
            'Pro klienty, kteří chtějí pouze využít maximalizaci daňových výhod životního pojištění',
            'Pro klienty, kteří chtějí využít max. státní příspěvky',
            'Pro klienty, kteří se chtějí dobře zajistit proti úrazům',
          ],
          correctAnswer: 'Pro klienty, kteří chtějí pouze využít maximalizaci daňových výhod životního pojištění',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q56',
          text: 'U benefitu Zvýhodněné plnění při párové smrti, dojde k vyplacení jednorázové poj. částky ve výši:',
          options: [
            '5 násobku pojistné částky sjedané u pojištění Smrti',
            '5 násobku pojistné částky sjedané u pojištění Smrti při dopravní nehodě',
            '5 násobku pojistné částky sjedané u pojištění Smrti úrazem',
          ],
          correctAnswer: '5 násobku pojistné částky sjedané u pojištění Smrti při dopravní nehodě',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q103',
          text: 'Z pojištění Asistované reprodukce vyplatíme klientce maximálně :',
          options: ['30 000 Kč', '50 000 Kč', '100 000 Kč'],
          correctAnswer: '100 000 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q7',
          text: 'DNL-MAX vyplácíme?',
          options: [
            'Když léčení trvá min. 30 dnů, dle Oceňovacích tabulek',
            'Podle skutečné doby léčení, která trvala min.3 dny',
            'Dle Oceňovacích tabulek a zároveň doba léčení trvá min. 8 dnů',
          ],
          correctAnswer: 'Dle Oceňovacích tabulek a zároveň doba léčení trvá min. 8 dnů',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q92',
          text: 'Lze indexaci při sjednání smlouvy vyloučit?',
          options: ['Ano', 'NE', 'Ano, na prvních 5 let'],
          correctAnswer: 'NE',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q72',
          text: 'Jaké je minimální pojistné v brandu Můj život PROFI 2?',
          options: ['200 Kč měsíčně za rizika i investice', '200 Kč měsíčně za rizika a 100 Kč na investice', '200 Kč měsíčně za rizika'],
          correctAnswer: '200 Kč měsíčně za rizika i investice',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q83',
          text: 'Na jak dlouhou dobu je možné sjednat pojištění Můj život 2?',
          options: ['3 - 81 let', '18 - 96 let', 'Na dobu neurčitou'],
          correctAnswer: '3 - 81 let',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q95',
          text: 'Co je Věrnostní prémie?',
          options: [
            'Výplata prémie až 15 000 Kč po polovině odžité pojistné doby',
            'Dřívější výplata Věrnostního bonusu z pojistného za dítě',
            'Sleva z pojistného 20 % za sjednání rizik pro děti',
          ],
          correctAnswer: 'Dřívější výplata Věrnostního bonusu z pojistného za dítě',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q112',
          text: 'Pokud dojde k výplatě poj. plnění za dg. Rakovina ve stadiu in-situ:',
          options: [
            'Zaniká Závažné onemocnění, rozšířená i základní varianta',
            'Zaniká pouze rozšířená varianta závažného onemocnění',
            'Závažné onemocnění nezaniká',
          ],
          correctAnswer: 'Závažné onemocnění nezaniká',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q115',
          text: 'Čekací doba pro riziko Ošetřování dospělého je:',
          options: ['1. měsíc od sjednání', '2. měsíce od sjednání', '6. měsíců od sjednání'],
          correctAnswer: '2. měsíce od sjednání',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q42',
          text: 'Pojistná částka za závažná poranění je vyplacena:',
          options: ['Po ustálení následků úrazu', 'Po stanovení diagnózy', 'Po přešetření následků úrazu posudkovým lékařem GČP'],
          correctAnswer: 'Po stanovení diagnózy',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q69',
          text: 'Kolik osob lze pojistit v brandu Můj život na PENZI 2?',
          options: ['Až 4 osoby', 'Pouze 1 osobu', 'Neomezeně'],
          correctAnswer: 'Pouze 1 osobu',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q81',
          text: 'Jaké je minimální pojistné v pojištění Můj život 2?',
          options: ['Riziková část 300 Kč + investiční část min. 100 Kč', '200 Kč', 'Riziková část 300 Kč + investiční část min. 1 Kč'],
          correctAnswer: 'Riziková část 300 Kč + investiční část min. 1 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q41',
          text: 'Pojištění Závažná poranění zaniká po výplatě pojistného plnění.',
          options: ['Ano', 'Ne', 'Ano, ale jen v případě, kdy došlo k plnění z rozšířené varianty'],
          correctAnswer: 'Ne',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q67',
          text: 'Jaké je minimální pojistné v brandu Můj život na PENZI 2?',
          options: [
            '200 Kč za celou poj. smlouvu do investic + pojistné za povinnou smrt',
            '300 Kč',
            '100 Kč za celou poj. smlouvu do investic + pojistné za povinnou smrt',
          ],
          correctAnswer: '200 Kč za celou poj. smlouvu do investic + pojistné za povinnou smrt',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q112',
          text: 'Pokud dojde k výplatě poj. plnění za dg. Rakovina ve stadiu in-situ:',
          options: [
            'Závažné onemocnění nezaniká',
            'Zaniká pouze rozšířená varianta závažného onemocnění',
            'Zaniká Závažné onemocnění, rozšířená i základní varianta',
          ],
          correctAnswer: 'Závažné onemocnění nezaniká',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q15',
          text: 'Benefit Program proti rakovině je sjednán automaticky vždy:',
          options: [
            'Když je sjednaná pojistná částka pro případ závažného onemocnění min. 200 000 Kč',
            'Když je sjednané pojištění Závažného onemocnění',
            'Když je sjednaná pojistná částka pro případ závažného onemocnění min. 100 000 Kč',
          ],
          correctAnswer: 'Když je sjednaná pojistná částka pro případ závažného onemocnění min. 200 000 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
      ],
    },
    {
      id: 'property',
      name: 'Můj majetek 2.0',
      questions: [
        {
          id: 'q6_1',
          text: 'Je možné LP Stavba, Domácnost, Jiná stavba, ATYP v produktu Můj majetek 2.0 uvést do role pojištěného i IČO?',
          options: [
            'pouze pokud je fyzická osoba podnikající',
            'ano, fyzická osoba podnikající i právnická osoba podnikající',
            'ne, IČO může být pouze v roli pojistníka',
          ],
          correctAnswer: 'ano, fyzická osoba podnikající i právnická osoba podnikající',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q31_1',
          text: 'Asistenci můžeme rozdělit do:',
          options: ['dvou okruhů - start a cíl', 'nerozdělujeme', 'tří okruhů - technická, právní a IT'],
          correctAnswer: 'tří okruhů - technická, právní a IT',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q46_1',
          text: 'Je základní asistence povinná?',
          options: ['Ne', 'Ano', 'Základní asistence je volitelná a záleží na klientovi, zda se pro ni rozhodne.'],
          correctAnswer: 'Ano',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q57_1',
          text: 'Jakou maximální škodu může žádat zaměstnavatel po svém zaměstnanci:',
          options: [
            'čtyřapůlnásobek jeho průměrného měsíčního výdělku',
            'čtyřnásobek jeho průměrného měsíčního výdělku',
            'pětinásobek jeho průměrného měsíčního výdělku',
          ],
          correctAnswer: 'čtyřapůlnásobek jeho průměrného měsíčního výdělku',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q36_1',
          text: 'V domácnosti nepojistíme:',
          options: ['Věci pronajímatele', 'Věci podnájemníků', 'Věci nájemníků'],
          correctAnswer: 'Věci podnájemníků',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q14_1',
          text: 'U pojištění domácnosti v produktu Můj majetek 2.0 je limit pro samostatně nebytové prostory:',
          options: [
            'limitem na první riziko',
            'samostatným limitem nad pojistnou částku domácnosti',
            'sublimitem pojistné částky domácnosti',
          ],
          correctAnswer: 'samostatným limitem nad pojistnou částku domácnosti',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q40_1',
          text: 'Jakou je možno poskytnout slevu na pojistném, pokud je v pojištění staveb pojišťována budova ve výstavbě nebo novostavba (nikoli rekonstrukce stávajícího objektu)?',
          options: [
            'Trvalá sleva ve výši 40 %, pokud byla stavba zahájena do 1 měsíce od vydání stavebního povolení.',
            'automatickou slevu za novostavbu ve výši 5% (navíc je možné uplatnit obchodní slevu)',
            'Ve výši 30 %, pokud byla smlouva sepsána do 12 měsíců od vydání stavebního povolení.',
          ],
          correctAnswer: 'automatickou slevu za novostavbu ve výši 5% (navíc je možné uplatnit obchodní slevu)',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q19_1',
          text: 'Co nelze pojistit v rámci pojištění domácnosti?',
          options: [
            'Soubor hmotných movitých věcí, které tvoří vybavení domácnosti.',
            'Stavební součásti tvořící vnitřní prostor bytu a souvisejících prostor.',
            'Hodnotu věcí, která vyplývá z autorského práva.',
          ],
          correctAnswer: 'Hodnotu věcí, která vyplývá z autorského práva.',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q24_1',
          text: 'Vedlejší stavba (LP Stavba):',
          options: ['Nesmí být určena k bydlení', 'Může být určena k bydlení', 'Nepojistíme'],
          correctAnswer: 'Může být určena k bydlení',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q20_1',
          text: 'U volitelného připojištění Porosty na pozemku a zahradní architektura nepojistíme:',
          options: ['živé ploty', 'jednoleté rostliny', 'trvalky'],
          correctAnswer: 'jednoleté rostliny',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q47_1',
          text: 'Základní asistence je:',
          options: ['Zdarma, pokud má člověk sjednáno pojištění odpovědnosti.', 'Zdarma', 'Za 1,- ročně.'],
          correctAnswer: 'Zdarma',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q23_1',
          text: 'Nebytové prostory v rámci domácnosti lze pojistit:',
          options: [
            'Pouze na adrese, kde se nachází pojištěná domácnost',
            'Kdekoliv na území ČR',
            'Pouze v obci, kde se nachází pojištěná domácnost',
          ],
          correctAnswer: 'Kdekoliv na území ČR',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q2',
          text: 'Pojištění Mazlíček je určeno pro:',
          options: ['Psy a kočky', 'Exotická zvířata', 'Jakákoliv malá domácí zvířata (max. do velikosti ovcí a koz)'],
          correctAnswer: 'Psy a kočky',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q6',
          text: 'U pojištění Mazlíček lze na jedné smlouvě pojistit:',
          options: [
            'Až 5 zvířat včetně jejich vzájemné kombinace',
            'Až 10 zvířat včetně jejich vzájemné kombinace',
            'Až 3 zvířata včetně jejich vzájemné kombinace',
          ],
          correctAnswer: 'Až 5 zvířat včetně jejich vzájemné kombinace',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q10_1',
          text: 'Co to jsou v rámci pojistných podmínek pro Můj majetek 2.0 ekologické náklady?',
          options: [
            'tento pojem se přímo ve VPP nevyskytuje, jedná se o žolíka, kdy pojišťovna v případě totální škody na LP stavba vyplatí dvojnásobek PČ',
            'tento pojem se přímo ve VPP nevyskytuje, ale jedná se o náklady, které pojišťovna vyplatí v případě částečné škody',
            'tento pojem se přímo ve VPP nevyskytuje, ale jedná se o náklady, které budou vyplaceny nad PČ u LP Stavba a to v případě škody nad 50 % pojistné částky',
          ],
          correctAnswer:
            'tento pojem se přímo ve VPP nevyskytuje, ale jedná se o náklady, které budou vyplaceny nad PČ u LP Stavba a to v případě škody nad 50 % pojistné částky',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q8_1',
          text: 'Jak jsou pojištěny porosty na pozemku v rámci LP Stavba?',
          options: [
            'jako připojištění a to na jednoznačně vyjmenovaná pojistná nebezpečí dle VPP – živel, vodovodní škody, P/Z, odcizení, vandal, sprejer, přepětí, sklo',
            'jako předmět pojištění a to na všechna pojistná nebezpečí sjednaná v PS – dle sjednaného typu balíčku',
            'jako předmět pojištění a to na jednoznačně vyjmenovaná pojistná nebezpečí dle VPP – živel, vodovodní škody, P/Z, odcizení, vandal, sprejer, přepětí, sklo',
          ],
          correctAnswer:
            'jako připojištění a to na jednoznačně vyjmenovaná pojistná nebezpečí dle VPP – živel, vodovodní škody, P/Z, odcizení, vandal, sprejer, přepětí, sklo',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q58_1',
          text: 'Kolektivní odpovědnost lze sjednat od:',
          options: ['8 osob', '10 osob', '15 osob'],
          correctAnswer: '10 osob',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q45_1',
          text: 'Pojištění odpovědnosti z běžného občanského života se nevztahuje na:',
          options: ['Jízdu na motokárách', 'Létání s dronem', 'Jízda na koni'],
          correctAnswer: 'Jízdu na motokárách',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q1_1',
          text: 'V jaké ceně bude v případě poškození pojišťovna plnit z pojištění domácnosti, pokud byla časová cena pojištěné věci (sedací souprava) bezprostředně před vznikem pojistné události nižší než 50 % její nové ceny?',
          options: ['V nové ceně', 'V obvyklé ceně', 'V časové ceně'],
          correctAnswer: 'V nové ceně',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q29_1',
          text: 'V LP Pojištění obytných budov, bytů a souvisejících staveb pojistíme mimo jiné:',
          options: [
            'stavební materiál, dočasné objekty zařízení staveniště s výjimkou stavebních mechanismů a nářadí potřebné ke stavbě, údržbě a rekonstrukci',
            'stavební materiál, dočasné objekty zařízení staveniště, stavební mechanismy potřebné ke stavbě, údržbě a rekonstrukci s výjimkou nářadí',
            'stavební materiál, dočasné objekty zařízení staveniště, stavební mechanismy a nářadí potřebné ke stavbě, údržbě a rekonstrukci s výjimkou ručního nářadí',
          ],
          correctAnswer:
            'stavební materiál, dočasné objekty zařízení staveniště, stavební mechanismy a nářadí potřebné ke stavbě, údržbě a rekonstrukci s výjimkou ručního nářadí',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q59_1',
          text: 'Pojištění odpovědnosti z výkonu povolání se nevztahuje (pokud není ujednáno jinak) na:',
          options: ['GIBS (Generální inspekce bezpečnostních sborů)', 'Policie ČR', 'Hasičský záchranný sbor'],
          correctAnswer: 'Hasičský záchranný sbor',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q60_1',
          text: 'Připojištění Ztráty svěřených věcí se nevztahuje:',
          options: ['Ztrátu mobilního telefonu', 'Ztrátu univerzálního klíče od celé firmy', 'Odcizení mobilního telefonu'],
          correctAnswer: 'Odcizení mobilního telefonu',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q50_1',
          text: 'Jaká je podmínka pro sjednání Chytrého cestovního pojištění?',
          options: ['Žádná podmínka není', 'Sjednání občanské odpovědnosti', 'Sjednání pojištění staveb nebo pojištění domácnosti'],
          correctAnswer: 'Žádná podmínka není',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q27_1',
          text: 'V případě pojištění sportovního vybavení v Atyp – AKTIV:',
          options: [
            'Musíme ve smlouvě identifikovat předmět pojištění, pokud poptávaný limit je vyšší než 100 tis. Kč.',
            'Nemusíme ve smlouvě identifikovat předmět pojištění.',
            'Musíme ve smlouvě identifikovat předmět pojištění.',
          ],
          correctAnswer: 'Musíme ve smlouvě identifikovat předmět pojištění, pokud poptávaný limit je vyšší než 100 tis. Kč.',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q26_1',
          text: 'V rozsahu pojištění Atyp – Zahradní technika je místem pojištění:',
          options: [
            'Adresa včetně nebytových prostor, pozemek (zahrada či dvůr) jenž je v jednotném funkčním celku s místem pojištění',
            'Adresa včetně nebytových prostor, pozemek (zahrada či dvůr) jenž je v jednotném funkčním celku s místem pojištění a bezprostřední okolí mimo toto místo.',
            'Adresa včetně nebytových prostor',
          ],
          correctAnswer:
            'Adresa včetně nebytových prostor, pozemek (zahrada či dvůr) jenž je v jednotném funkčním celku s místem pojištění',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q48_1',
          text: 'Jaký je maximální počet výjezdů do zahraničí v rámci Chytrého cestovního pojištění?',
          options: ['Není omezen', '36 výjezdů za rok', '10 výjezdů za rok'],
          correctAnswer: 'Není omezen',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q56_1',
          text: 'Musí být osoby, které chci pojistit chytrým pojištěním uvedeny ve smlouvě?',
          options: [
            'Nemusí, pojištění se automaticky vztahuje na osoby, kteří žijí ve společné domácnosti – manžel/ka, partner/ka, registrovaný partner/ka a děti do 26 let.',
            'Ano, všechny osoby musí být uvedeny v roli pojištěný',
            'Nemusí, pokud to jsou příbuzní v řadě přímé.',
          ],
          correctAnswer: 'Ano, všechny osoby musí být uvedeny v roli pojištěný',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q7_1',
          text: 'Jsou předmětem pojištění v rámci pojištění staveb vířivky (myšleno pevné, nikoli nafukovací)',
          options: [
            'ne',
            'ano, jsou pojištěny v rámci vedlejších staveb',
            'ano, ale pouze pokud je zapuštěná minimálně z 1/2 své výšky v okolním terénu',
          ],
          correctAnswer: 'ano, jsou pojištěny v rámci vedlejších staveb',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q32_1',
          text: 'Trvale užívaným bytem se rozumí byt obývaný více jak:',
          options: ['180 dnů v roce', '120 dnů v roce', '60 dnů v roce'],
          correctAnswer: '180 dnů v roce',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q54_1',
          text: 'Chytré cestovní pojištění se vztahuje na tyto typy cest:',
          options: [
            'turistické a poznávací cesty, studijní pobyty, rekreační sporty',
            'turistické, pracovní poznávací cesty, studijní pobyty, rekreační sporty',
            'turistické a poznávací cesty, studijní pobyty, rekreační sporty a organizovaný sport',
          ],
          correctAnswer: 'turistické, pracovní poznávací cesty, studijní pobyty, rekreační sporty',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q15_1',
          text: 'Pokud jsou v novém produktu Můj majetek 2.0 movité věci umístěny v nebytových prostorech přímo komunikačně propojených s bytem pojištěné domácnosti (LP pojištění domácnosti), tak hodnota těchto věcí se:',
          options: [
            'je pojištěna na první riziko',
            'se započítává do pojistné částky pojištěné domácnosti',
            'započítává do limitu pro nebytové prostory',
          ],
          correctAnswer: 'se započítává do pojistné částky pojištěné domácnosti',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q33_1',
          text: 'V domácnosti nepojistíme:',
          options: ['zvířata chovaná k výdělečné činnosti', 'věci sloužící k výdělečné činnosti', 'věci návštěv'],
          correctAnswer: 'zvířata chovaná k výdělečné činnosti',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q52_1',
          text: 'Chytré cestovní pojištění lze sjednat max. do věku:',
          options: ['70 let', '65 let', 'Není žádný věkový limit'],
          correctAnswer: 'Není žádný věkový limit',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q49_1',
          text: 'Jaká je maximální nepřetržitá délka pobytu v zahraničí v rámci Chytrého cestovního pojištění?',
          options: ['max. 30 dní', 'Není stanovena', 'max. 60 dní'],
          correctAnswer: 'max. 60 dní',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q39_1',
          text: 'Je možné u pojištění staveb získat bonus na pojistném za bezeškodní průběh?',
          options: ['Ano, za každý rok pojištění 5 %, max. 20 %.', 'Ne', 'Ano, pouze u smluv na dobu neurčitou.'],
          correctAnswer: 'Ne',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q30_1',
          text: 'Asistence je rozdělena:',
          options: [
            'do tří variant - Základ, Nadstandard a Premium',
            'do dvou variant - Základ a Nadstandard',
            'do čtyř variant - Start, Standard, Exclusiv a Comfort',
          ],
          correctAnswer: 'do dvou variant - Základ a Nadstandard',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q25_1',
          text: 'Kdy využívám pojištění Atyp?',
          options: [
            'Když žádným ze standardních pojištění není možné uspokojit zcela individuální potřeby klienta.',
            'Když se obchodník domnívá, že daná věc v domácnosti (např. drahá podlahová krytina) by měla být pojištěna se se souhlasem upisovatele.',
            'Když nemohu najít položku, kterou bych danou stavbu (vedlejší stavbu) pojistil.',
          ],
          correctAnswer: 'Když žádným ze standardních pojištění není možné uspokojit zcela individuální potřeby klienta.',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q53_1',
          text: 'Jaký je limit na léčebné výlohy u Chytrého cestovního pojištění:',
          options: ['50 000 000', '80 000 000', '100 000 000'],
          correctAnswer: '100 000 000',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q16_1',
          text: 'Do jakého limitu jsou automaticky pojištěny vedlejší stavby v rámci LP Stavba v novém produktu Můj majetek 2.0?',
          options: [
            '15 % ze základní pojistné částky stavby',
            '5 % ze základní pojistné částky stavby',
            '20 % ze základní pojistné částky stavby',
          ],
          correctAnswer: '15 % ze základní pojistné částky stavby',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q22_1',
          text: 'V jakém limitu je vzdálená pomoc u IT asistence?',
          options: ['45min/5x ročně', '60min/5x ročně', '30min/5x ročně'],
          correctAnswer: '60min/5x ročně',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q42_1',
          text: 'U pojištění odpovědnosti v běžném občanském životě jsou spolu s pojištěným také pojištění:',
          options: [
            'manžel/ka, druh/družka, registr.partner, děti do 30 let (musí být svobodné, bezdětné a s pojištěným sdílet společnou domácnost)',
            'Vedle pojištěného jsou dalšími spolupojištěnými osobami všechny fyzické osoby,které spolu s pojištěným trvale žijí ve společné domácnosti a podílí se na jejím chodu.',
            'manžel/ka, druh/družka, registr.partner, děti do 18 let (musí být svobodné, bezdětné a s pojištěným sdílet společnou domácnost)',
          ],
          correctAnswer:
            'Vedle pojištěného jsou dalšími spolupojištěnými osobami všechny fyzické osoby,které spolu s pojištěným trvale žijí ve společné domácnosti a podílí se na jejím chodu.',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q18_1',
          text: 'Připojištění Aktiv, které se týká jakéhokoliv sportovního vybavení oprávněných osob sloužící k soukromému použití pro amatérský sport, se sjednává s územním rozsahem:',
          options: ['Evropa', 'Svět', 'Česká republika'],
          correctAnswer: 'Svět',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q12_1',
          text: 'Pojištění bytové jednotky sjednáváme v produktu Můj majetek 2.0 na:',
          options: ['pojistnou částku v nové hodnotě', 'limit plnění', 'pojistnou částka se zohledněním tržních faktorů'],
          correctAnswer: 'pojistnou částka se zohledněním tržních faktorů',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q55_1',
          text: 'Musí všechny osoby pojištěné chytrým cestovním pojištěním cestovat společně?',
          options: ['Ano', 'Ne', 'Nemusí, pokud tuto skutečnost oznámí pojišťovně minimálně 24 hod. před započetím cesty'],
          correctAnswer: 'Ne',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q2_1',
          text: 'Klientovi byl odcizen mobilní telefon z auta. Kdy je tato událost likvidní z pojištění domácnosti?',
          options: [
            'Pokud byl telefon v uzavřeném zavazadlovém prostoru',
            'Pokud byl telefon na palubní desce.',
            'Tato událost není likvidní.',
          ],
          correctAnswer: 'Pokud byl telefon v uzavřeném zavazadlovém prostoru',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q44_1',
          text: 'LP Asistence je u pojištění domásnosti nebo obytných budov, bytů a souvisejících staveb:',
          options: ['Nelze sjednat.', 'Povinná.', 'Nepovinná, ale je zdarma.'],
          correctAnswer: 'Povinná.',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q17_1',
          text: 'Vedlejší stavby lze pojistit bez nutnosti úpisu maximálně na:',
          options: ['Na 30 % sjednané pojistné částky pro pojištěnou stavbu.', '5 milionů Kč.', '2 miliony Kč.'],
          correctAnswer: '5 milionů Kč.',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q3_1',
          text: 'Uhradíme z pojištění skla a sanity škody na rámech a osazeních, popř. skleněných mozaikách a jiných formách uměleckého zasklení?',
          options: ['max. 20% za sjednaného limitu', 'ano', 'ne'],
          correctAnswer: 'ano',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q13_1',
          text: 'Bytové jednotky jsou v produktu Můj majetek 2.0:',
          options: ['indexovány indexem cen stavebních děl', 'nejsou indexovány', 'indexovány indexem stavebních prací'],
          correctAnswer: 'indexovány indexem stavebních prací',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q11_1',
          text: 'Vodovodní škody lze u produktu Můj majetek 2.0 odpojistit:',
          options: [
            'u staveb a domácností obydlených méně než 180 dnů v kalendářním roce',
            'u staveb obydlených méně než 250 v kalendářním roce',
            'u staveb obydlených méně než 200 v kalendářním roce',
          ],
          correctAnswer: 'u staveb a domácností obydlených méně než 180 dnů v kalendářním roce',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q21_1',
          text: 'Pokud sjednávám LP Domácnost nebo LP Stavba je povinné sjednat základní asistenci?',
          options: ['Základní asistence je volitelná a záleží na klientovi, zda se pro ni rozhodne.', 'Ano', 'Ne'],
          correctAnswer: 'Ano',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q35_1',
          text: 'V pojištění Můj majetek 2.0 můžeme pojistit:',
          options: [
            'Pouze jednu domácnost',
            'Až pět domácností – pro každou je nutné uvést místo pojištění.',
            'Až tři domácnosti – pro každou je nutné uvést místo pojištění.',
          ],
          correctAnswer: 'Až pět domácností – pro každou je nutné uvést místo pojištění.',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q41_1',
          text: 'Pro dětský kočárek platí v pojištění domácnosti územní rozsah (popř. místo pojištění):',
          options: ['Evropa', 'Svět', 'Česká republika'],
          correctAnswer: 'Svět',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q9_1',
          text: 'U vodovodních škod - lom trubky je limit:',
          options: ['není limit', '200.000', '100.000'],
          correctAnswer: 'není limit',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q5_1',
          text: 'Jak správně pojistit kuchyňskou linku?',
          options: [
            'v rámci pojištění domácnosti musí být pojištěna vždy a to v rámci souboru hmotných movitých věcí',
            've stavbě a v pojištění domácnosti ji považujeme za stavební součásti (o její hodnotu musí být navýšen limit pro stavební součásti)',
            'v atypu',
          ],
          correctAnswer:
            've stavbě a v pojištění domácnosti ji považujeme za stavební součásti (o její hodnotu musí být navýšen limit pro stavební součásti)',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q51_1',
          text: 'Součástí chytrého cestovního pojištění není:',
          options: ['Pojištění odpovědnosti', 'Sublimit na akutní ošetření zubů', 'Pojištění cestovních zavazadel'],
          correctAnswer: 'Pojištění odpovědnosti',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q1_mazlicek',
          text: 'Pojištění mazlíček nabízí možnost výběru:',
          options: [
            'Ze dvou balíčků – Základ a Nadstandard',
            'Ze tří balíčků – Start, Standard, Exklusive',
            'Ze čtyř balíčků – Start, Standard, Exklusive, Comfort',
          ],
          correctAnswer: 'Ze tří balíčků – Start, Standard, Exklusive',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q31_1',
          text: 'Jinou stavbou lze mimo jiné pojistit i zahradní chatku do:',
          options: ['25m2', '15m2', '10m2'],
          correctAnswer: '25m2',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q34_1',
          text: 'U domácnosti podpojištění:',
          options: ['Uplatňujeme, pokud je PČ nižší o 20% než je pojistná hodnota', 'Uplatňujeme vždy', 'Neuplatňujeme'],
          correctAnswer: 'Uplatňujeme, pokud je PČ nižší o 20% než je pojistná hodnota',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q37_1',
          text: 'V pojištění domácnosti jsou za věci za pozemku považovány:',
          options: [
            'zahradní nábytek, dětské herní prvky, zahradní grily, bazény, které nejsou vedlejší stavbou a nafukovací vířivky včetně příslušenství k nim, zvířata (nikoli ale chovaná k výdělečným účelům) a jejich přibytky',
            'jen zahradní nábytek, dětské herní prvky a zahradní grily',
            'jen zahradní nábytek a zahradní grily',
          ],
          correctAnswer:
            'zahradní nábytek, dětské herní prvky, zahradní grily, bazény, které nejsou vedlejší stavbou a nafukovací vířivky včetně příslušenství k nim, zvířata (nikoli ale chovaná k výdělečným účelům) a jejich přibytky',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q10_ekologicke_naklady',
          text: 'Co to jsou v rámci pojistných podmínek pro Můj majetek 2.0 ekologické náklady?',
          options: [
            'tento pojem se přímo ve VPP nevyskytuje, ale jedná se o náklady, které budou vyplaceny nad PČ u LP Stavba a to v případě škody nad 50 % pojistné částky',
            'tento pojem se přímo ve VPP nevyskytuje, ale jedná se o náklady, které pojišťovna vyplatí v případě částečné škody',
            'tento pojem se přímo ve VPP nevyskytuje, jedná se o žolíka, kdy pojišťovna v případě totální škody na LP stavba vyplatí dvojnásobek PČ',
          ],
          correctAnswer:
            'tento pojem se přímo ve VPP nevyskytuje, ale jedná se o náklady, které budou vyplaceny nad PČ u LP Stavba a to v případě škody nad 50 % pojistné částky',
          correctCount: 0,
          incorrectCount: 0,
        },
      ],
    },
    {
      id: 'investice',
      name: 'Investice',
      questions: [
        {
          id: 'q123',
          text: 'Jaká je výše vstupního poplatku při vložení 100 000 Kč do Generali fondu konzervativního?',
          options: ['0 Kč', '1000 Kč', '100 Kč'],
          correctAnswer: '0 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q124',
          text: 'Bude Generali Prémiový vyvážený fond vhodné doporučit klientovi, který je klasifikován jako velmi opatrný?',
          options: [
            'Ano, fond je dostatečně konzervativní pro takového klienta',
            'Ano, ale pouze na dlouhý investiční horizont (min. 8 let), doporučení vyplývá z produktové matice',
            'Ne, velmi opatrnému klientovi lze doporučit pouze fondy peněžního trhu',
          ],
          correctAnswer: 'Ano, ale pouze na dlouhý investiční horizont (min. 8 let), doporučení vyplývá z produktové matice',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q125',
          text: 'Je možné současně zvolit poradenský i zprostředkovatelský způsob jednání?',
          options: [
            'Ne, je možné zvolit pouze jeden způsob a výběr je na klientovi',
            'Ne, vždy musím jednat poradensky',
            'Ano, způsoby lze kombinovat',
          ],
          correctAnswer: 'Ne, je možné zvolit pouze jeden způsob a výběr je na klientovi',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q126',
          text: 'Jaké je SRI fondu globálních značek?',
          options: ['4 -5', '2-3', '1-2'],
          correctAnswer: '4 -5',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q127',
          text: 'Kolik % akcií lze očekávat v portfoliu Generali Fond balancovaného dynamického',
          options: ['80% - 90%', '60 % v neutrálním scénáři', 'max 15%'],
          correctAnswer: '60 % v neutrálním scénáři',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q128',
          text: 'Jaký vstupní poplatek byste očekávali u Generali Fond balancovaného dynamického',
          options: ['0% - 2%', '0%', '1,8% - 3,0%'],
          correctAnswer: '1,8% - 3,0%',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q129',
          text: 'Kde najdu přehled alternativních produktů vhodných pro klientův výsledný rizikový profil, pokud klient nesouhlasí s produktem v doporučení (radě)?',
          options: [
            'Takovýto přehled neexistuje, záleží na výběru poradce',
            'V investiční kalkulačce Generali Investments',
            'V produktové matici, které je vyvěšena na obchodním portále',
          ],
          correctAnswer: 'V produktové matici, které je vyvěšena na obchodním portále',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q130',
          text: 'Který z těchto fondů byste vybrali pro vytváření střednědobé rezervy:',
          options: ['Fond globálních značek', 'Fond Korporátních dluhopisů', 'Prémiový dynamický fond'],
          correctAnswer: 'Fond Korporátních dluhopisů',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q131',
          text: 'Který z těchto fondů byste vybrali pro vytváření dlouhodobé rezervy:',
          options: ['Prémiový konzervativní fond', 'Prémiový dynamický fond', 'Fond Korporátních dluhopisů'],
          correctAnswer: 'Prémiový dynamický fond',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q132',
          text: 'U kterého z fondů je plně v kompetenci portfolio manažera skladba podkladových aktiv?',
          options: ['Prémiový dynamický fond', 'Fond korporátních dluhopisů', 'Fond globálních značek'],
          correctAnswer: 'Prémiový dynamický fond',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q133',
          text: 'Co klient neobdrží poštou po uzavření návrhu smlouvy?',
          options: ['Heslo pro webovou aplikaci', 'Potvrzení o uzavření smlouvy', 'Debetní kartu k ČP kontu'],
          correctAnswer: 'Debetní kartu k ČP kontu',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q134',
          text: 'Vyberte správné tvrzení:',
          options: [
            'Investiční program Generali Rezerva je složený převážně z akcií',
            'Investiční program Generali Rezerva je složený převážně z korporátních dluhopisů',
            'Investiční program Generali Rezerva je složený převážně ze státních dluhopisů',
          ],
          correctAnswer: 'Investiční program Generali Rezerva je složený převážně z korporátních dluhopisů',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q135',
          text: 'Jaké je výše minimální měsíční investice do třídy fondů s označením P?',
          options: ['20 000 Kč', '1000 Kč', '10 000 Kč'],
          correctAnswer: '10 000 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q136',
          text: 'Jaké je výše minimální měsíční investice do třídy fondů s označením R?',
          options: ['100 Kč', '1 000 Kč', '500 Kč'],
          correctAnswer: '500 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q137',
          text: 'Jaký domicil mají fondy GICEE?',
          options: ['ČR a Francie', 'ČR a Irsko', 'Pouze ČR'],
          correctAnswer: 'ČR a Irsko',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q138',
          text: 'Jaká bude výše poplatku u produktu Partner Invest Plus, když se klient rozhodne investovat 500 Kč měsíčně po dobu 20 let.',
          options: ['2440 Kč', '4800 Kč', '4440 Kč'],
          correctAnswer: '4440 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q139',
          text: 'Proč je potřeba při modelaci Partner Investu plus zadávat rok narození klienta?',
          options: [
            'Protože Generali Investments eviduje věkovou strukturu klientů',
            'Protože produkt nelze sjednat klientům nad 75 let',
            'Protože na základě tohoto údaje systém ohlídá maximální možnou dobu předplácení poplatku s ohledem na věk klienta',
          ],
          correctAnswer:
            'Protože na základě tohoto údaje systém ohlídá maximální možnou dobu předplácení poplatku s ohledem na věk klienta',
          correctCount: 0,
          incorrectCount: 0,
        },
      ],
    },
    {
      id: 'auto',
      name: 'Moje auto',
      questions: [
        {
          id: 'q10',
          text: 'Jaké fixní spoluúčasti lze v havarijním pojištění sjednat?',
          options: [
            '1 000 Kč, 5 000 Kč, 10 000 Kč, 20 000 Kč, 30 000 Kč nebo speciální po schválení upisovatelem',
            '1 000 Kč, 5 000 Kč, 10 000 Kč, 20 000 Kč nebo speciální',
            '1 000 Kč, 2 000 Kč, 5 000 Kč, 20 000 Kč nebo speciální',
          ],
          correctAnswer: '1 000 Kč, 5 000 Kč, 10 000 Kč, 20 000 Kč, 30 000 Kč nebo speciální po schválení upisovatelem',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q3',
          text: 'Jaká je spoluúčast u pojištění všech skel?',
          options: ['Bez spoluúčasti', '300,-Kč', '1%, min. 1 000,-Kč'],
          correctAnswer: 'Bez spoluúčasti',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q17',
          text: 'Jaký je limit plnění u doplňkového pojištění střet se zvířetem?',
          options: ['50 000 Kč', '100 000 Kč na pojistný rok', '150 000 Kč'],
          correctAnswer: '100 000 Kč na pojistný rok',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q24',
          text: 'Které asistence mají službu zapůjčení náhradního vozidla?',
          options: ['S, M, L, XL a Souprava', 'M, L, XL a Souprava', 'L, XL a Souprava'],
          correctAnswer: 'L, XL a Souprava',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q28',
          text: 'Co je podmínkou vyplacení pojistného plnění u doplňkového pojištění střet se zvířetem?',
          options: [
            'na místo nehody musí být přivolána Policie ČR nebo Asistenční služba GČP',
            'doložení protokolu lesní správy',
            'kamerový záznam ze střetu',
          ],
          correctAnswer: 'na místo nehody musí být přivolána Policie ČR nebo Asistenční služba GČP',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q29',
          text: 'Jaká je spoluúčast, limit a územní rozsah u doplňkového pojištění poškození vozidla - NEROVNOST VOZOVKY?',
          options: [
            'spoluúčast 1 000 Kč, limit 15 000 Kč na pojistné období, územní rozsah ČR',
            'spoluúčast 5 000 Kč, limit 15 000 Kč na pojistné období, územní rozsah ČR',
            'spoluúčast 1 000 Kč, limit 30 000 Kč na pojistné období, územní rozsah ČR',
          ],
          correctAnswer: 'spoluúčast 1 000 Kč, limit 15 000 Kč na pojistné období, územní rozsah ČR',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q11',
          text: 'Co určuje hodnotu vozidla v HAV All Risk?',
          options: ['cena budoucí', 'pojistná částka', 'limit plnění'],
          correctAnswer: 'pojistná částka',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q23',
          text: 'Která asistence nemá nastaven celkový limit pojistného plnění u odtahů?',
          options: ['M', 'XL', 'S'],
          correctAnswer: 'XL',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q15',
          text: 'Jaký územní rozsah má doplňkové pojištění poškození všech skel?',
          options: [
            'Česká republika',
            'Svět',
            'Geografické území Evropy a Turecka, s výjimkou Arménie, Ázerbájdžánu, Běloruska, Gruzie, Moldavska, Ruska a Ukrajiny',
          ],
          correctAnswer:
            'Geografické území Evropy a Turecka, s výjimkou Arménie, Ázerbájdžánu, Běloruska, Gruzie, Moldavska, Ruska a Ukrajiny',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q2',
          text: 'Jaké varianty havarijního pojištění máme v produktové nabídce?',
          options: [
            'ALL Risk, ALL Risk 6+, Havárie a živel',
            'ALL Risk, Havárie, Odcizení, Čelní sklo',
            'ALL Risk, ALL Risk 6+, Havárie a živel, Odcizení a živel',
          ],
          correctAnswer: 'ALL Risk, ALL Risk 6+, Havárie a živel, Odcizení a živel',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q30',
          text: 'Které balíčky doplňkových pojištění, sjednané spolu s POV, obsahují v základu přímou likvidaci?',
          options: ['Premium, Exclusive a Standart', 'Premium a Exclusive', 'všechny'],
          correctAnswer: 'všechny',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q27',
          text: 'Co je podmínkou pro zaplacení škody na všech vnějších částech vozidla u doplňkového pojištění poškození vozidla - VANDAL',
          options: [
            'vlastní fotky poškozeného vozidla',
            'kamerový záznam zachycující vznik a průběh pojistné události',
            'čestné prohlášení majitele vozidla',
          ],
          correctAnswer: 'kamerový záznam zachycující vznik a průběh pojistné události',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q26',
          text: 'Jaká je spoluúčast u doplňkového pojištění poškození vozidla zvířetem?',
          options: ['pojištění se sjednává bez spoluúčasti pro ČR', '1 000 Kč', '10% minimálně 10 000 Kč'],
          correctAnswer: '1 000 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q6a',
          text: 'Na které varianty POV mohu připojistit garanci ceny?',
          options: [
            'pouze na varianty s limitem 150, 200 a 300 mio. Kč',
            'pouze na varianty s limitem 200 a 300 mio. Kč',
            'na všechny varianty POV a pokud je na smlouvě i HAV All Risk, tak je garance ceny na obou produktech',
          ],
          correctAnswer: 'na všechny varianty POV a pokud je na smlouvě i HAV All Risk, tak je garance ceny na obou produktech',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q14',
          text: 'Která pojistná nebezpečí kryje pojištění všech skel?',
          options: ['havárie, živel a vandalismus', 'havárie, živel, odcizení a vandalismus', 'havárie a živel'],
          correctAnswer: 'havárie, živel, odcizení a vandalismus',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q12',
          text: 'Jaká je územní platnost povinného ručení?',
          options: ['Česká republika', 'Celý svět', 'Česká republika a cizí státy uvedené na zelené kartě'],
          correctAnswer: 'Česká republika a cizí státy uvedené na zelené kartě',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q31',
          text: 'V havarijním pojištění All Risk 6+ jsou na výběr tyto limity plnění:',
          options: ['40, 80 a 100 tis. Kč', '60, 80 a 100 tis. Kč', '30, 60, 80 a 100 tis. Kč'],
          correctAnswer: '60, 80 a 100 tis. Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q4',
          text: 'K čemu je připojištění garance ceny?',
          options: [
            'garantujeme nezdražení u třech prvních škod',
            'garantujeme nezdražení po dobu 5 let',
            'garantujeme nezdražení pojistného po dobu 3 let a první škoda nemá vliv na zdražení pojistného u dané pojistné smlouvy',
          ],
          correctAnswer:
            'garantujeme nezdražení pojistného po dobu 3 let a první škoda nemá vliv na zdražení pojistného u dané pojistné smlouvy',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q5',
          text: 'Která z uvedených situací je likvidní z povinného ručení?',
          options: [
            'škody na zdraví nebo usmrcení osob, které nebyly ve vozidle, jehož provozem byla škoda způsobena',
            'škoda na věci, kterou utrpěl řidič vozidla, jehož provozem byla škoda způsobena',
            'škoda na vozidle, jehož provozem byla škoda způsobena',
          ],
          correctAnswer: 'škody na zdraví nebo usmrcení osob, které nebyly ve vozidle, jehož provozem byla škoda způsobena',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q20',
          text: 'Který balíček doplňkových pojištění má v základním rozsahu asistenci XL?',
          options: ['STANDART', 'START', 'PREMIUM'],
          correctAnswer: 'PREMIUM',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q1',
          text: 'Jaká je územní platnost havarijního pojištění GČP?',
          options: [
            'Celý svět',
            'Geografické území Evropy a Turecka, s výjimkou Arménie, Ázerbájdžánu, Běloruska, Gruzie, Moldavska, Ruska a Ukrajiny',
            'Evropa bez ČR',
          ],
          correctAnswer:
            'Geografické území Evropy a Turecka, s výjimkou Arménie, Ázerbájdžánu, Běloruska, Gruzie, Moldavska, Ruska a Ukrajiny',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q13',
          text: 'Ve kterém z uvedených příkladů musíme provést fotodokumentaci vozidla:',
          options: [
            'sjednání havarijního pojištění v jakékoli variantě',
            'sjednání pouze povinného ručení',
            'sjednání povinného ručení a asistence',
          ],
          correctAnswer: 'sjednání havarijního pojištění v jakékoli variantě',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q19',
          text: 'Vztahuje se doplňkové pojištění poškození nebo odcizení zavazadel na výpočetní techniku?',
          options: ['ne', 'ano, ale pouze na notebook', 'ano'],
          correctAnswer: 'ne',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q16',
          text: 'Bezlimitní skla lze sjednat:',
          options: [
            'v rámci jakéhokoli balíčku doplňkových pojištění',
            'pouze v rámci nejvyššího balíčku doplňkových pojištění PREMIUM a v kombinaci s HAV',
            'pouze v rámci individuálního nastavení doplňkových pojištění',
          ],
          correctAnswer: 'pouze v rámci nejvyššího balíčku doplňkových pojištění PREMIUM a v kombinaci s HAV',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q29',
          text: 'Jaká je spoluúčast, limit a územní rozsah u doplňkového pojištění poškození vozidla - NEROVNOST VOZOVKY?',
          options: [
            'spoluúčast 1 000 Kč, limit 30 000 Kč na pojistné období, územní rozsah ČR',
            'spoluúčast 1 000 Kč, limit 15 000 Kč na pojistné období, územní rozsah ČR',
            'spoluúčast 5 000 Kč, limit 15 000 Kč na pojistné období, územní rozsah ČR',
          ],
          correctAnswer: 'spoluúčast 1 000 Kč, limit 15 000 Kč na pojistné období, územní rozsah ČR',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q140',
          text: 'Jaké je výše minimální měsíční investice do třídy fondů s označením R?',
          options: ['100 Kč', '500 Kč', '1 000 Kč'],
          correctAnswer: '500 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q141',
          text: 'Který z programů GICEE je sestaven z Generali Prémiových fondů',
          options: ['Partner Invest plus', 'Generali rezerva', 'Trend 3'],
          correctAnswer: 'Partner Invest plus',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q142',
          text: 'O čem v názvu Generali Prémiového konzervativního fondu svědčí slovo "Prémiový"',
          options: [
            'Fond je řízen velmi aktivně a může měnit obsah podkladových aktiv',
            'Fond investuje převážně do cenných papírů prémiových značek',
            'Fond je primárně určen pro vybrané klienty',
          ],
          correctAnswer: 'Fond investuje převážně do cenných papírů prémiových značek',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q143',
          text: 'Který z těchto fondů je výrazně orientován na domácí český trh?',
          options: ['Fond globálních značek', 'Fond krátkodobých investic', 'Prémiový dynamický fond'],
          correctAnswer: 'Fond krátkodobých investic',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q144',
          text: 'Vyberte správné parametry produktu Partner Invest Plus',
          options: [
            'Doba trvání při sjednání 5 - 40 let, maximálně do 65 let věku klienta, vklad minimálně 500 Kč měsíčně, nulový vstupní poplatek, investiční brzda',
            'Doba trvání při sjednání 3 - 50 let roky, vklad minimálně 300 Kč měsíčně, nulový výstupní poplatek',
            'Doba trvání při sjednání 5-40 let, maximálně do 65 let věku klienta, vklad minimálně 500 Kč měsíčně, poplatek dle cílové částky či měsíčního vkladu, investiční brzda',
          ],
          correctAnswer:
            'Doba trvání při sjednání 5-40 let, maximálně do 65 let věku klienta, vklad minimálně 500 Kč měsíčně, poplatek dle cílové částky či měsíčního vkladu, investiční brzda',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q145',
          text: 'Jaká je výše vstupního poplatku při vložení 100 000 Kč do Generali fondu konzervativního?',
          options: ['100 Kč', '1000 Kč', '0 Kč'],
          correctAnswer: '0 Kč',
          correctCount: 0,
          incorrectCount: 0,
        },
        {
          id: 'q146',
          text: 'Který z těchto fondů byste vybrali pro vytváření krátkodobé rezervy:',
          options: ['Fond Korporátních dluhopisů', 'Fond globálních značek', 'Prémiový dynamický fond'],
          correctAnswer: 'Fond Korporátních dluhopisů',
          correctCount: 0,
          incorrectCount: 0,
        },
      ],
    },
  ],
  activeCategory: 'property',
}
